// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reset.sql

package database

import (
	"context"
)

const deleteEverything = `-- name: DeleteEverything :exec
DELETE FROM users
`

func (q *Queries) DeleteEverything(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteEverything)
	return err
}
